### ISSUE TITLE
Error opening app: The app provided is not a valid electron app

### ISSUE THREAD

**Issue by ivomarsan** [henriquesosa/electron-intro#1]
Recebi o erro:

```
Error opening app
The app provided is not a valid electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/master/docs
```

Poderia atualizar? Seria de grande valia :smiley:

**Comment by henriquesosa** [comment]
@ivomarsan você tentou rodar o o app pelo comando `electron app` ou via `gulp` ?

**Comment by ivomarsan** [comment]
Utilizei as 2 formas. Por sinal, ele não conseguiu localizar o módulo app. Estranho?

**Comment by ivomarsan** [comment]
Nossa, acabei de descobrir o erro, localizado no `package.json`

**Comment by henriquesosa** [comment]
poderia fazer um pull request corrigindo?
